[build]
  functions = "netlify/functions"
  publish = 'src'


[[redirects]]
  from = "/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"